/**
 * Generate template code from wizard state
 * Separated to avoid JSX/template literal conflicts
 */

export function generateTemplateCode(state) {
    const {
        templateName = "My Template",
        templateDescription = "My custom template",
        hasHeroForm = true,
        hasCalculator = false,
        hasTestimonials = false,
        hasFAQ = false,
        hasTrustBadges = false,
        hasDarkMode = false,
        includeTracking = true
    } = state;

    // Simple template code
    const code = `/**
 * ${templateName} Template
 * ${templateDescription}
 * Auto-generated by Template Generator Wizard
 */

import { COLORS, FONTS } from '../../core/template-registry.js';

export function generate(site) {
  const c = COLORS.find(x => x.id === site.colorId) || COLORS[0];
  const f = FONTS.find(x => x.id === site.fontId) || FONTS[0];
  const brand = site.brand || "${templateName}";
  const domain = site.domain || "example.com";

  const files = {};

  // ─── package.json ────────────────────────────────────────
  files["package.json"] = JSON.stringify({
    name: brand.toLowerCase().replace(/[^a-z0-9]/g, "-"),
    version: "1.0.0",
    type: "module",
    scripts: { dev: "astro dev", build: "astro build", preview: "astro preview" },
    dependencies: { astro: "^5.2.0" },
  }, null, 2);

  // ─── astro.config.mjs ────────────────────────────────────
  files["astro.config.mjs"] = \`import { defineConfig } from "astro/config";
export default defineConfig({ output: "static", site: "https://" + domain });\`;

  // ─── src/pages/index.astro ────────────────────────────────
  const h1 = site.h1 || "Your Headline";
  const sub = site.sub || "Your subheadline";
  const cta = site.cta || "Get Started";

  files["src/pages/index.astro"] = \`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>\\\${brand}</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: system-ui, sans-serif; line-height: 1.6; }
      .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
      .hero { min-height: 80vh; display: flex; align-items: center; justify-content: center; }
      .btn { padding: 16px 32px; background: #3b82f6; color: white; border: none; border-radius: 8px; font-size: 16px; cursor: pointer; }
    </style>
    ${includeTracking ? '<script>window.dataLayer = window.dataLayer || [];</script>' : ''}
  </head>
  <body>
    <section class="hero">
      <div class="container" style="text-align: center;">
        <h1>\\\${h1}</h1>
        <p>\\\${sub}</p>
        ${hasHeroForm ? `<form onsubmit="handleSubmit(event)"><input type="email" placeholder="Email" required style="padding: 12px; margin-right: 8px;" /><button type="submit" class="btn">\\\${cta}</button></form>` : `<a href="#apply" class="btn">\\\${cta}</a>`}
      </div>
    </section>
    ${hasTrustBadges ? '<section style="padding: 60px 20px; text-align: center;"><div>🔒 Secure · ⚡ Fast · ✓ Trusted</div></section>' : ''}
    ${hasFAQ ? '<section style="padding: 60px 20px;"><details><summary>FAQ</summary><p>Answer here</p></details></section>' : ''}
    <footer style="padding: 40px 20px; text-align: center; background: #1a1a1a; color: white;">
      <p>© \\\${new Date().getFullYear()} \\\${brand}</p>
    </footer>
    ${includeTracking ? '<script>function handleSubmit(e){e.preventDefault();window.dataLayer.push({event:"lead"});}</script>' : ''}
  </body>
</html>\`;

  return files;
}

// Register in templates/index.js:
// registerTemplate('${templateName.toLowerCase().replace(/[^a-z0-9]/g, "-")}', {
//   name: '${templateName}',
//   description: '${templateDescription}',
//   badge: 'New',
//   category: 'general',
//   generate: generate,
// });
`;

    return code;
}
